### ISSUE TITLE
Local image shows blank in slideshow

### ISSUE THREAD

**Issue by KirankumarDafda** [haqiqiw/react-native-slideshow#11]
How to add local image to the url so it shows in the slideshow, i have tried below urls but none works for me

`<Slideshow
	dataSource={[
	{ url:'./images/restImage.jpg' }
]}/>`

or 

`<Slideshow
	dataSource={[
	{ url:'images/restImage.jpg' }
]}/>`

Make sure that the same source ('./images/restImage.jpg') is working fine with image element, so there is no any path issue i think.

**Comment by Hajar1** [comment]
+1

**Comment by arsomjin** [comment]
I've the same issue. I try ..
dataSource={[ { url: require('images/restImage.jpg') } ]}
works for me.

**Comment by KirankumarDafda** [comment]
It works. Thank you.
